language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
      - llvm-toolchain-xenial-7
      - llvm-toolchain-xenial-6
      - llvm-toolchain-xenial-5
      - llvm-toolchain-xenial-4
      - llvm-toolchain-xenial-3
    packages:
      - g++-9
      - g++-8
      - g++-7
      - g++-6
      - g++-5
      - g++-4
      - clang-8
      - clang-7
      - clang-6
      - clang-5
      - clang-4
      - clang-3
      - cmake

install:
  # Install Gtest
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz && cd googletest-release-1.10.0
  - mkdir build && cd build
  - cmake .. && make -j8
  - sudo make install

matrix:
  include:
    - env: Run Clang Tests
      before_script:
        - export CC=clang-8 && export CXX=clang++-8
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j8
      script:
        - ./Tests
    - env: Run GCC Tests
      before_script:
        - export CC=gcc-9 && export CXX=g++-9
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j8
      script:
        - ./Tests