language: cpp

before_script:
  - $CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DSERIO_BUILD_TESTS=ON ..
  - make -j$(nproc)

script:
  - ./tests

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: OSX 7.3 AMD64 Clang

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: OSX 8 AMD64 Clang

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: OSX 8.3 AMD64 Clang

    - os: osx
      osx_image: xcode9
      compiler: clang
      env: OSX 9 AMD64 Clang

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: OSX 9.1 AMD64 Clang

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: OSX 9.2 AMD64 Clang

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: OSX 9.3 AMD64 Clang

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: OSX 9.4 AMD64 Clang

    - os: osx
      osx_image: xcode10
      compiler: clang
      env: OSX 10 AMD64 Clang

    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: OSX 10.1 AMD64 Clang

    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: OSX 10.2 AMD64 Clang

    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: OSX 10.3 AMD64 Clang

    - os: osx
      osx_image: xcode11
      compiler: clang
      env: OSX 11 AMD64 Clang

    - os: osx
      osx_image: xcode11.1
      compiler: clang
      env: OSX 11.1 AMD64 Clang

    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env: OSX 11.2 AMD64 Clang

    - os: osx
      osx_image: xcode11.3
      compiler: clang
      env: OSX 11.3 AMD64 Clang

    - os: osx
      osx_image: xcode11.4
      compiler: clang
      env: OSX 11.4 AMD64 Clang

    - os: osx
      osx_image: xcode11.5
      compiler: clang
      env: OSX 11.5 AMD64 Clang

    - os: osx
      osx_image: xcode11.6
      compiler: clang
      env: OSX 11.6 AMD64 Clang

    - os: osx
      osx_image: xcode12
      compiler: clang
      env: OSX 12 AMD64 Clang

    - os: osx
      osx_image: xcode12u
      compiler: clang
      env: OSX 12u AMD64 Clang



    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 3.6
        - CC=clang-3.6
        - CXX=clang++-3.6
      addons:
        apt:
          packages:
            - clang-3.6

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 3.7
        - CC=clang-3.7
        - CXX=clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 3.8
        - CC=clang-3.8
        - CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 3.9
        - CC=clang-3.9
        - CXX=clang++-3.9
      addons:
        apt:
          packages:
            - clang-3.9

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 4.0
        - CC=clang-4.0
        - CXX=clang++-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 5.0
        - CC=clang-5.0
        - CXX=clang++-5.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 6.0
        - CC=clang-6.0
        - CXX=clang++-6.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 7
        - CC=clang-7
        - CXX=clang++-7
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 8
        - CC=clang-8
        - CXX=clang++-8
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 9
        - CC=clang-9
        - CXX=clang++-9
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-9
          packages:
            - clang-9

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 Clang 10
        - CC=clang-10
        - CXX=clang++-10
      addons:
        apt:
          packages:
            - clang-10



    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 5
        - CC=gcc-5
        - CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 6
        - CC=gcc-6
        - CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 7
        - CC=gcc-7
        - CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 8
        - CC=gcc-8
        - CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 9
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9

    - os: linux
      arch: arm64
      dist: xenial
      env:
        - Linux ARM64 GCC 10
        - CC=gcc-10
        - CXX=g++-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10



    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 3.6
        - CC=clang-3.6
        - CXX=clang++-3.6
      addons:
        apt:
          packages:
            - clang-3.6

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 3.7
        - CC=clang-3.7
        - CXX=clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 3.8
        - CC=clang-3.8
        - CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 3.9
        - CC=clang-3.9
        - CXX=clang++-3.9
      addons:
        apt:
          packages:
            - clang-3.9

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 4.0
        - CC=clang-4.0
        - CXX=clang++-4.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 5.0
        - CC=clang-5.0
        - CXX=clang++-5.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 6.0
        - CC=clang-6.0
        - CXX=clang++-6.0
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 7
        - CC=clang-7
        - CXX=clang++-7
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 8
        - CC=clang-8
        - CXX=clang++-8
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 9
        - CC=clang-9
        - CXX=clang++-9
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-9
          packages:
            - clang-9

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 Clang 10
        - CC=clang-10
        - CXX=clang++-10
      addons:
        apt:
          packages:
            - clang-10



    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 5
        - CC=gcc-5
        - CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 6
        - CC=gcc-6
        - CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 7
        - CC=gcc-7
        - CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 8
        - CC=gcc-8
        - CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 9
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9

    - os: linux
      dist: xenial
      env:
        - Linux AMD64 GCC 10
        - CC=gcc-10
        - CXX=g++-10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gcc-10

