language: cpp
dist: xenial

install:
  # Install Gtest
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz && cd googletest-release-1.10.0
  - mkdir build && cd build
  - cmake .. && make -j$(nproc)
  - sudo make install && cd ../..
 
before_script:
  - $CXX --version
  - cmake --version
  - mkdir build && cd build
  - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release .. && make -j$(nproc)

script:
  - ./Tests

matrix:
  include:

    - env: CC=clang-8 && export CXX=clang++-8
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8

    - env: CC=clang-7 && export CXX=clang++-7
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7

    - env: CC=clang-6 && export CXX=clang++-6
      addons:
        apt:
          packages:
            - clang-6

    - env: CC=clang-5 && export CXX=clang++-5
      addons:
        apt:
          packages:
            - clang-5

    - env: CC=clang-4 && export CXX=clang++-4
      addons:
        apt:
          packages:
            - clang-4

    - env: CC=clang-3.9 && export CXX=clang++-3.9
      addons:
        apt:
          packages:
            - clang-3.9

    - env: CC=clang-3.8 && export CXX=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8

    - env: CC=clang-3.7 && export CXX=clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7

    - env: CC=clang-3.6 && export CXX=clang++-3.6
      addons:
        apt:
          packages:
            - clang-3.6

    - env: CC=gcc-9 && export CXX=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9

    - env: CC=gcc-8 && export CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - env: CC=gcc-7 && export CXX=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    - env: CC=gcc-6 && export CXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - env: CC=gcc-5 && export CXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: CC=gcc-4.9 && export CXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

    - env: CC=gcc-4.8 && export CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
