language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
      - llvm-toolchain-xenial-7
    packages:
      - g++-9
      - g++-8
      - g++-7
      - g++-6
      - g++-5
      - g++-4
      - gcc-9
      - gcc-8
      - gcc-7
      - gcc-6
      - gcc-5
      - gcc-4
      - clang-8
      - clang-7
      - cmake

install:
  # Install Gtest
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz && cd googletest-release-1.10.0
  - mkdir build && cd build
  - cmake .. && make -j$(nproc)
  - sudo make install
 
before_script:
  - mkdir build && cd build
  - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)

script:
  - ./Tests

matrix:
  include:
    - env: export CC=clang-8 && export CXX=clang++-8
    - env: Clang 7 Tests
      before_script:
        - export CC=clang-7 && export CXX=clang++-7
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 9 Tests
      before_script:
        - export CC=gcc-9 && export CXX=g++-9
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 8 Tests
      before_script:
        - export CC=gcc-8 && export CXX=g++-8
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 7 Tests
      before_script:
        - export CC=gcc-7 && export CXX=g++-7
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 6 Tests
      before_script:
        - export CC=gcc-6 && export CXX=g++-6
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 5 Tests
      before_script:
        - export CC=gcc-5 && export CXX=g++-5
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests
    - env: GCC 4 Tests
      before_script:
        - export CC=gcc-4 && export CXX=g++-4
        - mkdir build && cd build
        - cmake -DBUILD_TESTS=ON .. && make -j$(nproc)
      script:
        - ./Tests